name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Arduino-Zephyr-API

      - name: Initialize
        working-directory: Arduino-Zephyr-API
        run: |
          west init -m https://github.com/arduino/ArduinoCore-zephyr.git
          west update
          git clone https://github.com/arduino/ArduinoCore-API.git ArduinoCore-API
          cp -r ArduinoCore-API/api modules/lib/Arduino-Zephyr-API/cores/arduino/.

      - name: Build fade
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b arduino_nano_33_ble//sense samples/fade

      - name: Build i2cdemo
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b arduino_nano_33_ble//sense samples/i2cdemo

      - name: Build adc
        working-directory: Arduino-Zephyr-API
        run: |
          west build -p -b beagleconnect_freedom samples/analog_input

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: Arduino-Zephyr-API/build/zephyr/zephyr.*
