name: 'Format Check'

on:
  push:
    branches:
      - 'main'

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - 'main'

jobs:
  verify-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false
      - name: Get changed source files that need format check
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            cores/arduino/**/*.{c,cpp,h,hpp}
            loader/**/*.{c,cpp,h,hpp}
            libraries/**/*.{c,cpp,h,hpp}
          files_ignore: |
            cores/arduino/api/**
            loader/llext_exports.c
            loader/blobs/4343WA1_*.c
            loader/blobs/wifi_nvram_image.h
            libraries/examples/**
            libraries/extras/**
            libraries/ea_malloc/**
          json: true
      - name: Export changed files in a text file, one per line
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -r '.[]' > all_changed_files.txt
          cat all_changed_files.txt
      - name: Run clang-format check
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: pillo79/clang-format-action@05f671e71f0758aba4d3c9dbb0ee81bc5f0137c6
        with:
          clang-format-version: '19'
          check-files-from: all_changed_files.txt
