name: Package core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk-0.16.8
    steps:
      - name: Install toolchain
        working-directory: /opt
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip ninja-build
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz && cd zephyr-sdk-0.16.8 && ./setup.sh -t arm-zephyr-eabi -c

      - uses: actions/checkout@v4

      - name: Initialize
        run: |
          ./extra/bootstrap.sh
          ./extra/build_all.sh
          ./extra/package.sh `git describe --always`
          mv ../arduino-core-zephyr-llext* .

      - name: Archive core
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: arduino-core-zephyr-llext*
