name: Package core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /home/runner/work/ArduinoCore-zephyr/zephyr-sdk-0.16.8
    steps:
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz && cd zephyr-sdk-0.16.8 && ./setup.sh -t arm-zephyr-eabi -c
          mv zephyr-sdk-0.16.8 ../

      - name: Initialize
        run: |
          ./extra/bootstrap.sh
          ./extra/build_all.sh
          ./extra/package.sh `git describe --always`

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: arduino-core-zephyr-llext*
